###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    code-web:
        image: nginx:alpine
        container_name: code-web
        working_dir: /application
        volumes:
            - ${VOLUME_PATH}:/application
            - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
        ports:
            - ${PORT_HTTP}:80

    code-php:
        build: phpdocker/php-fpm
        container_name: code-php
        working_dir: /application
        volumes:
            - ${VOLUME_PATH}:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        ports:
            - ${PORT_PHP}:9000
